---
plugins:
  - react
  - import
  - babel
  - '@typescript-eslint'
env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
    impliedStrict: true
    modules: true
settings:
  import/resolver:
    typescript:
      project: ./tsconfig.json
    webpack: webpack.config.js
  react:
    version: '16.14.0'
overrides:
  -
    files:
      - '**/*.tsx'
      - '**/*.ts'
    extends: plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/ban-ts-ignore': off
      '@typescript-eslint/ban-types': warn
      '@typescript-eslint/ban-ts-comment': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/prefer-interface': off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/indent':
        - error
        - 4
        - SwitchCase: 0
      '@typescript-eslint/no-use-before-define':
        - error
        - classes: false
          functions: false
          variables: false
      react/jsx-filename-extension:
        - warn
        - extensions:
            - .jsx
            - .tsx
rules:
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  arrow-body-style: off
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  block-scoped-var: error
  brace-style: off
  '@typescript-eslint/brace-style':
    - error
    - stroustrup
    - allowSingleLine: true
  capitalized-comments: off
  class-methods-use-this: off
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  complexity:
    - off
    - 10
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this:
    - error
    - self
  constructor-super: error
  curly:
    - error
    - all
  dot-location:
    - error
    - object
  dot-notation: error
  eqeqeq:
    - error
    - smart
  func-call-spacing:
    - error
    - never
  func-name-matching: off
  func-names: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  generator-star-spacing:
    - error
    - before: false
      after: true
  global-require: error
  guard-for-in: error
  id-blacklist: off
  import/no-unresolved: error
  import/order:
    - error
    - newlines-between: always-and-inside-groups
      groups:
        - builtin
        - external
        -
          - internal
          - parent
        - sibling
        - index
  indent:
    - error
    - 4
    - SwitchCase: 0
  jsx-quotes:
    - error
    - prefer-single
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - error
    - before: true
      after: true
      overrides: {}
  line-comment-position: off
  linebreak-style: error
  lines-around-comment:
    - error
    - beforeBlockComment: true
      beforeLineComment: true
      allowBlockStart: true
      allowBlockEnd: true
  max-lines:
    - warn
    - max: 450
      skipBlankLines: true
      skipComments: false
  max-nested-callbacks:
    - error
    - max: 2
  max-statements-per-line:
    - error
    - max: 1
  multiline-ternary:
    - warn
    - never
  new-cap: error
  new-parens: error
  newline-before-return: off
  newline-per-chained-call: off
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-caller: error
  no-case-declarations: error
  no-class-assign: error
  no-compare-neg-zero: error
  no-cond-assign:
    - error
    - except-parens
  no-confusing-arrow: error
  no-console: error
  no-const-assign: error
  no-constant-condition: error
  no-debugger: error
  no-div-regex: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports:
    - error
    - includeExports: true
  no-else-return: error
  no-empty: error
  no-empty-function: error
  no-empty-pattern: error
  no-eval: error
  no-ex-assign: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: off
  no-extra-semi: error
  no-fallthrough: error
  no-floating-decimal: error
  no-func-assign: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: off
  no-implied-eval: error
  no-inner-declarations: off
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers:
    - off
    - ignore:
        - -1
        - 0
        - 1
        - 2
      enforceConst: true
      detectObjects: true
  no-mixed-operators:
    - error
    - allowSamePrecedence: false
  no-mixed-spaces-and-tabs: error
  no-multi-assign: error
  no-multi-spaces:
    - error
    - exceptions:
        Property: false
  no-multi-str: off
  no-multiple-empty-lines:
    - error
    - max: 1
  no-native-reassign: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-symbol: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-redeclare: error
  no-return-assign:
    - error
    - always
  no-return-await: error
  no-script-url: error
  no-self-assign:
    - error
    - props: true
  no-self-compare: error
  no-sequences: error
  no-shadow:
    - error
    - hoist: functions
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-tabs: off
  no-template-curly-in-string: error
  no-ternary: off
  no-this-before-super: error
  no-throw-literal: error
  no-trailing-spaces:
    - error
    - skipBlankLines: false
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: error
  no-unexpected-multiline: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary:
    - error
    - defaultAssignment: false
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  no-unused-expressions: error
  no-unused-vars:
    - error
    - vars: all
      args: after-used
  no-use-before-define:
    - error
    - classes: false
      functions: false
      variables: false
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-useless-return: error
  no-var: off
  no-void: error
  no-warning-comments: warn
  no-whitespace-before-property: error
  no-with: error
  object-curly-newline: off
  object-curly-spacing:
    - error
    - never
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  object-shorthand:
    - error
    - always
  one-var:
    - error
    - never
  one-var-declaration-per-line: off
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - after
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: off
  prefer-numeric-literals: error
  prefer-promise-reject-errors: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: off
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - avoid-escape
  radix: error
  react/display-name:
    - off
    - ignoreTranspilerName: false
  react/forbid-component-props: off
  react/forbid-elements:
    - error
    - forbid:
      - embed
  react/jsx-boolean-value:
    - error
    - always
  react/jsx-closing-bracket-location:
    - error
    - location: tag-aligned
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
  react/jsx-filename-extension: error
  react/jsx-first-prop-new-line:
    - error
    - multiline
  react/jsx-handler-names: off
  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react/jsx-key: error
  react/jsx-max-props-per-line:
    - error
    - maximum: 1
  react/jsx-no-bind: off
  react/jsx-no-comment-textnodes: error
  react/jsx-no-duplicate-props:
    - error
    - ignoreCase: false
  react/jsx-no-literals: error
  react/jsx-no-target-blank: error
  react/jsx-no-undef: error
  react/jsx-pascal-case: error
  react/jsx-tag-spacing:
    - error
    - closingSlash: never
      beforeSelfClosing: never
      afterOpening: never
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: error
  react/no-array-index-key: warn
  react/no-children-prop: error
  react/no-danger: off
  react/no-danger-with-children: error
  react/no-deprecated: warn
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: warn
  react/no-is-mounted: error
  react/no-multi-comp:
    - error
    - ignoreStateless: true
  react/no-render-return-value: error
  react/no-set-state: off
  react/no-string-refs: off
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/no-unused-prop-types:
    - warn
    - skipShapeProps: true
  react/prefer-es6-class: error
  react/prefer-stateless-function: error
  react/prop-types:
    - error
    - ignore:
      - location
      - history
      - component
  react/require-default-props: off
  react/require-optimization: warn
  react/require-render-return: error
  react/self-closing-comp: error
  react/sort-comp: off
  react/style-prop-object: error
  require-yield: error
  rest-spread-spacing:
    - error
    - never
  semi:
    - error
    - always
  semi-spacing:
    - error
    - before: false
      after: true
  sort-imports: off
  sort-keys: off
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  symbol-description: error
  template-curly-spacing:
    - error
    - never
  valid-typeof:
    - error
    - requireStringLiterals: false
  vars-on-top: off
  wrap-iife:
    - error
    - outside
  wrap-regex: error
  yoda:
    - error
    - never
    - exceptRange: false
      onlyEquality: false
